### ISSUE TITLE
Question - Scoping Styles to Component

### ISSUE THREAD

**Issue by thomascgray** [rofrischmann/react-css-component#1]
Hello hello!

The library seems great 😃and almost exactly perfectly fits my use case - however, my concern is that the styles are in no way scoped to the component, correct?

i.e I have 2 components built using this library (X and Y), and they co-exist on one page at render. Because they both inject a `<style>` tag into the DOM, the styles from X can affect the presentation of Y? If for example they both use `<p>` tags, and X includes styles along the lines of `p { color: red }`

Am I correct in this line of thinking?

**Comment by robinweser** [comment]
Oh damn, I was for some reason not watching this repo and thus didn't see that issue :/ 

Still leaving an answer: Yeah, that's right. This library doesn't aim to solve class name conflicts and whatever. To achieve that, I'd actually recommend using a CSS in JS library.

You could also write a helper or sth. to generate unique class names for a given input if that helps.
